### ISSUE TITLE
素晴らしい記事です！useContextについてちょっと質問です。

### ISSUE THREAD

**Issue by sunderls** [uhyo/blog.uhy.ooo#14]
https://blog.uhy.ooo/entry/2021-07-24/react-state-management/#q--a

素晴らしい記事で勉強になりました！

>useContextを使うことで、ステートが変わった際には本当にそのステートを使用しているコンポーネントのみが再レンダリングされるようになるからです。コンポーネントツリーの頂点と使用者の間にある中間コンポーネントは、useContextを使っていなければ再レンダリングされません。

こうするには多分工夫する必要がありますね、context providerのchildrenを外に持ち出すか、memoするとかで。
デフォルトはこうならない気がします

**Comment by uhyo** [comment]
ありがとうございます 🙂 その通りなので、`React.memo`に対する言及を追記しました。
